var mongoose=require("mongoose");
var Product = require("./models/product");
var seeds =[
    {
        name:"sx",
        game:"PUBG Mobile",
        typeOfProduct:"Hack",
        device:"Gameloop",
        image:"https://i.ibb.co/ZL7DBJV/output-onlinepngtools.png",
        tutorial:"<p>Cream is <i>butter</i></p>",
        downloads:[
            {
             name:"SX",
             link:"https://mega.nz/#!4VVVEQCZ!AcURkXQy1lUFj2kPlb99H8OLtXYVa3aLzTxThBizhvk",
             version:"3.30"
            },
            {
             name:"SX",
             link:"https://www.lanzous.com/ia49hch",
             version:"3.10",
            }
        ],
        keys:[
            {
                keyType:"Day",
                keyPrice:"3",
                keyList:["daykey1","daykey2","daykey3"]
            },
            {
             keyType:"Week",
             keyPrice:"12",
             keyList:["weekkey1","weekkey2"]
            },
            {
             keyType:"Month",
             keyPrice:"18",
             keyList:["monthkey1"]  
             }
        ]
 
     },
    {
        name:"sx",
        game:"PUBG Mobile",
        typeOfProduct:"Hack",
        device:"Gameloop",
        image:"https://i.ibb.co/ZL7DBJV/output-onlinepngtools.png",
        tutorial:"<p>Cream is <i>butter</i></p>",
        downloads:[
            {
             name:"SX",
             link:"https://mega.nz/#!4VVVEQCZ!AcURkXQy1lUFj2kPlb99H8OLtXYVa3aLzTxThBizhvk",
             version:"3.30"
            },
            {
             name:"SX",
             link:"https://www.lanzous.com/ia49hch",
             version:"3.10",
            }
        ],
        keys:[
            {
                keyType:"Day",
                keyPrice:"3",
                keyList:["daykey1","daykey2","daykey3"]
            },
            {
             keyType:"Week",
             keyPrice:"12",
             keyList:["weekkey1","weekkey2"]
            },
            {
             keyType:"Month",
             keyPrice:"18",
             keyList:["monthkey1"]  
             }
        ]
 
     },
    {
        name:"sx",
        game:"PUBG Mobile",
        typeOfProduct:"Hack",
        device:"Gameloop",
        image:"https://i.ibb.co/ZL7DBJV/output-onlinepngtools.png",
        tutorial:"<p>Cream is <i>butter</i></p>",
        downloads:[
            {
             name:"SX",
             link:"https://mega.nz/#!4VVVEQCZ!AcURkXQy1lUFj2kPlb99H8OLtXYVa3aLzTxThBizhvk",
             version:"3.30"
            },
            {
             name:"SX",
             link:"https://www.lanzous.com/ia49hch",
             version:"3.10",
            }
        ],
        keys:[
            {
                keyType:"Day",
                keyPrice:"3",
                keyList:["daykey1","daykey2","daykey3"]
            },
            {
             keyType:"Week",
             keyPrice:"12",
             keyList:["weekkey1","weekkey2"]
            },
            {
             keyType:"Month",
             keyPrice:"18",
             keyList:["monthkey1"]  
             }
        ]
 
     },
    {
        name:"sx",
        game:"PUBG Mobile",
        typeOfProduct:"Hack",
        device:"Gameloop",
        image:"https://i.ibb.co/ZL7DBJV/output-onlinepngtools.png",
        tutorial:"<p>Cream is <i>butter</i></p>",
        downloads:[
            {
             name:"SX",
             link:"https://mega.nz/#!4VVVEQCZ!AcURkXQy1lUFj2kPlb99H8OLtXYVa3aLzTxThBizhvk",
             version:"3.30"
            },
            {
             name:"SX",
             link:"https://www.lanzous.com/ia49hch",
             version:"3.10",
            }
        ],
        keys:[
            {
                keyType:"Day",
                keyPrice:"3",
                keyList:["daykey1","daykey2","daykey3"]
            },
            {
             keyType:"Week",
             keyPrice:"12",
             keyList:["weekkey1","weekkey2"]
            },
            {
             keyType:"Month",
             keyPrice:"18",
             keyList:["monthkey1"]  
             }
        ]
 
     },
    {
        name:"sx",
        game:"PUBG Mobile",
        typeOfProduct:"Hack",
        device:"Gameloop",
        image:"https://i.ibb.co/ZL7DBJV/output-onlinepngtools.png",
        tutorial:"<p>Cream is <i>butter</i></p>",
        downloads:[
            {
             name:"SX",
             link:"https://mega.nz/#!4VVVEQCZ!AcURkXQy1lUFj2kPlb99H8OLtXYVa3aLzTxThBizhvk",
             version:"3.30"
            },
            {
             name:"SX",
             link:"https://www.lanzous.com/ia49hch",
             version:"3.10",
            }
        ],
        keys:[
            {
                keyType:"Day",
                keyPrice:"3",
                keyList:["daykey1","daykey2","daykey3"]
            },
            {
             keyType:"Week",
             keyPrice:"12",
             keyList:["weekkey1","weekkey2"]
            },
            {
             keyType:"Month",
             keyPrice:"18",
             keyList:["monthkey1"]  
             }
        ]
 
     },
    {
        name:"sx",
        game:"PUBG Mobile",
        typeOfProduct:"Hack",
        device:"Gameloop",
        image:"https://i.ibb.co/ZL7DBJV/output-onlinepngtools.png",
        tutorial:"<p>Cream is <i>butter</i></p>",
        downloads:[
            {
             name:"SX",
             link:"https://mega.nz/#!4VVVEQCZ!AcURkXQy1lUFj2kPlb99H8OLtXYVa3aLzTxThBizhvk",
             version:"3.30"
            },
            {
             name:"SX",
             link:"https://www.lanzous.com/ia49hch",
             version:"3.10",
            }
        ],
        keys:[
            {
                keyType:"Day",
                keyPrice:"3",
                keyList:["daykey1","daykey2","daykey3"]
            },
            {
             keyType:"Week",
             keyPrice:"12",
             keyList:["weekkey1","weekkey2"]
            },
            {
             keyType:"Month",
             keyPrice:"18",
             keyList:["monthkey1"]  
             }
        ]
 
     },
    {
        name:"sx",
        game:"PUBG Mobile",
        typeOfProduct:"Hack",
        device:"Gameloop",
        image:"https://i.ibb.co/ZL7DBJV/output-onlinepngtools.png",
        tutorial:"<p>Cream is <i>butter</i></p>",
        downloads:[
            {
             name:"SX",
             link:"https://mega.nz/#!4VVVEQCZ!AcURkXQy1lUFj2kPlb99H8OLtXYVa3aLzTxThBizhvk",
             version:"3.30"
            },
            {
             name:"SX",
             link:"https://www.lanzous.com/ia49hch",
             version:"3.10",
            }
        ],
        keys:[
            {
                keyType:"Day",
                keyPrice:"3",
                keyList:["daykey1","daykey2","daykey3"]
            },
            {
             keyType:"Week",
             keyPrice:"12",
             keyList:["weekkey1","weekkey2"]
            },
            {
             keyType:"Month",
             keyPrice:"18",
             keyList:["monthkey1"]  
             }
        ]
 
     },
    {
        name:"sx",
        game:"PUBG Mobile",
        typeOfProduct:"Hack",
        device:"Gameloop",
        image:"https://i.ibb.co/ZL7DBJV/output-onlinepngtools.png",
        tutorial:"<p>Cream is <i>butter</i></p>",
        downloads:[
            {
             name:"SX",
             link:"https://mega.nz/#!4VVVEQCZ!AcURkXQy1lUFj2kPlb99H8OLtXYVa3aLzTxThBizhvk",
             version:"3.30"
            },
            {
             name:"SX",
             link:"https://www.lanzous.com/ia49hch",
             version:"3.10",
            }
        ],
        keys:[
            {
                keyType:"Day",
                keyPrice:"3",
                keyList:["daykey1","daykey2","daykey3"]
            },
            {
             keyType:"Week",
             keyPrice:"12",
             keyList:["weekkey1","weekkey2"]
            },
            {
             keyType:"Month",
             keyPrice:"18",
             keyList:["monthkey1"]  
             }
        ]
 
     },
    {
        name:"sx",
        game:"PUBG Mobile",
        typeOfProduct:"Hack",
        device:"Gameloop",
        image:"https://i.ibb.co/ZL7DBJV/output-onlinepngtools.png",
        tutorial:"<p>Cream is <i>butter</i></p>",
        downloads:[
            {
             name:"SX",
             link:"https://mega.nz/#!4VVVEQCZ!AcURkXQy1lUFj2kPlb99H8OLtXYVa3aLzTxThBizhvk",
             version:"3.30"
            },
            {
             name:"SX",
             link:"https://www.lanzous.com/ia49hch",
             version:"3.10",
            }
        ],
        keys:[
            {
                keyType:"Day",
                keyPrice:"3",
                keyList:["daykey1","daykey2","daykey3"]
            },
            {
             keyType:"Week",
             keyPrice:"12",
             keyList:["weekkey1","weekkey2"]
            },
            {
             keyType:"Month",
             keyPrice:"18",
             keyList:["monthkey1"]  
             }
        ]
 
     },
    {
       name:"sx",
       game:"PUBG Mobile",
       typeOfProduct:"Hack",
       device:"Gameloop",
       image:"https://i.ibb.co/ZL7DBJV/output-onlinepngtools.png",
       tutorial:"<p>Cream is <i>butter</i></p>",
       downloads:[
           {
            name:"SX",
            link:"https://mega.nz/#!4VVVEQCZ!AcURkXQy1lUFj2kPlb99H8OLtXYVa3aLzTxThBizhvk",
            version:"3.30"
           },
           {
            name:"SX",
            link:"https://www.lanzous.com/ia49hch",
            version:"3.10",
           }
       ],
       keys:[
           {
               keyType:"Day",
               keyPrice:"3",
               keyList:["daykey1","daykey2","daykey3"]
           },
           {
            keyType:"Week",
            keyPrice:"12",
            keyList:["weekkey1","weekkey2"]
           },
           {
            keyType:"Month",
            keyPrice:"18",
            keyList:["monthkey1"]  
            }
       ]

    },
    {
        name:"paopao",
       game:"PUBG Mobile",
       typeOfProduct:"Hack",
       device:"Gameloop",
       status:"red",
       image:"https://i.ibb.co/ZL7DBJV/output-onlinepngtools.png",
       tutorial:"<p>Cream is <i>butter</i></p>",
       downloads:[
           {
            name:"SX",
            link:"https://mega.nz/#!4VVVEQCZ!AcURkXQy1lUFj2kPlb99H8OLtXYVa3aLzTxThBizhvk",
            version:"3.30"
           },
           {
            name:"SX",
            link:"https://www.lanzous.com/ia49hch",
            version:"3.10",
           }
       ],
       keys:[
           {
               keyType:"Day",
               keyPrice:"3",
               keyList:["daykey1","daykey2","daykey3"]
           },
           {
            keyType:"Week",
            keyPrice:"12",
            keyList:["weekkey1","weekkey2"]
           },
           {
            keyType:"Month",
            keyPrice:"18",
            keyList:["monthkey1"]  
            }
       ]
    },
    {
        name:"uspeed",
       game:"PUBG Mobile",
       typeOfProduct:"Hack",
       device:"Gameloop",
       image:"https://i.ibb.co/ZL7DBJV/output-onlinepngtools.png",
       tutorial:"<p>Cream is <i>butter</i></p>",
       downloads:[
           {
            name:"SX",
            link:"https://mega.nz/#!4VVVEQCZ!AcURkXQy1lUFj2kPlb99H8OLtXYVa3aLzTxThBizhvk",
            version:"3.30"
           },
           {
            name:"SX",
            link:"https://www.lanzous.com/ia49hch",
            version:"3.10",
           }
       ],
       keys:[
           {
               keyType:"Day",
               keyPrice:"3",
               keyList:["daykey1","daykey2","daykey3"]
           },
           {
            keyType:"Week",
            keyPrice:"12",
            keyList:["weekkey1","weekkey2"]
           },
           {
            keyType:"Month",
            keyPrice:"18",
            keyList:["monthkey1"]  
            }
       ]
    },
    {
        name:"loo",
       game:"PUBG Mobile",
       typeOfProduct:"Hack",
       device:"Gameloop",
       image:"https://i.ibb.co/ZL7DBJV/output-onlinepngtools.png",
       tutorial:"<p>Cream is <i>butter</i></p>",
       downloads:[
           {
            name:"SX",
            link:"https://mega.nz/#!4VVVEQCZ!AcURkXQy1lUFj2kPlb99H8OLtXYVa3aLzTxThBizhvk",
            version:"3.30"
           },
           {
            name:"SX",
            link:"https://www.lanzous.com/ia49hch",
            version:"3.10",
           }
       ],
       keys:[
           {
               keyType:"Day",
               keyPrice:"3",
               keyList:["daykey1","daykey2","daykey3"]
           },
           {
            keyType:"Week",
            keyPrice:"12",
            keyList:["weekkey1","weekkey2"]
           },
           {
            keyType:"Month",
            keyPrice:"18",
            keyList:["monthkey1"]  
            }
       ]
    },
    {
        name:"SX",
       game:"PUBG Mobile",
       typeOfProduct:"Hack",
       device:"Gameloop",
       image:"https://i.ibb.co/ZL7DBJV/output-onlinepngtools.png",
       tutorial:"<p>Cream is <i>butter</i></p>",
       downloads:[
           {
            name:"SX",
            link:"https://mega.nz/#!4VVVEQCZ!AcURkXQy1lUFj2kPlb99H8OLtXYVa3aLzTxThBizhvk",
            version:"3.30"
           },
           {
            name:"SX",
            link:"https://www.lanzous.com/ia49hch",
            version:"3.10",
           }
       ],
       keys:[
           {
               keyType:"Day",
               keyPrice:"3",
               keyList:["daykey1","daykey2","daykey3"]
           },
           {
            keyType:"Week",
            keyPrice:"12",
            keyList:["weekkey1","weekkey2"]
           },
           {
            keyType:"Month",
            keyPrice:"18",
            keyList:["monthkey1"]  
            }
       ]
    },
    {
        name:"SX",
       game:"PUBG Mobile",
       typeOfProduct:"Hack",
       device:"Gameloop",
       image:"https://i.ibb.co/ZL7DBJV/output-onlinepngtools.png",
       tutorial:"<p>Cream is <i>butter</i></p>",
       downloads:[
           {
            name:"SX",
            link:"https://mega.nz/#!4VVVEQCZ!AcURkXQy1lUFj2kPlb99H8OLtXYVa3aLzTxThBizhvk",
            version:"3.30"
           },
           {
            name:"SX",
            link:"https://www.lanzous.com/ia49hch",
            version:"3.10",
           }
       ],
       keys:[
           {
               keyType:"Day",
               keyPrice:"3",
               keyList:["daykey1","daykey2","daykey3"]
           },
           {
            keyType:"Week",
            keyPrice:"12",
            keyList:["weekkey1","weekkey2"]
           },
           {
            keyType:"Month",
            keyPrice:"18",
            keyList:["monthkey1"]  
            }
       ]
    },
    {
        name:"SX",
       game:"PUBG Mobile",
       typeOfProduct:"Hack",
       device:"Gameloop",
       image:"https://i.ibb.co/ZL7DBJV/output-onlinepngtools.png",
       tutorial:"<p>Cream is <i>butter</i></p>",
       downloads:[
           {
            name:"SX",
            link:"https://mega.nz/#!4VVVEQCZ!AcURkXQy1lUFj2kPlb99H8OLtXYVa3aLzTxThBizhvk",
            version:"3.30"
           },
           {
            name:"SX",
            link:"https://www.lanzous.com/ia49hch",
            version:"3.10",
           }
       ],
       keys:[
           {
               keyType:"Day",
               keyPrice:"3",
               keyList:["daykey1","daykey2","daykey3"]
           },
           {
            keyType:"Week",
            keyPrice:"12",
            keyList:["weekkey1","weekkey2"]
           },
           {
            keyType:"Month",
            keyPrice:"18",
            keyList:["monthkey1"]  
            }
       ]
    },
    {
        name:"SX",
       game:"PUBG Mobile",
       typeOfProduct:"Hack",
       device:"Gameloop",
       image:"https://i.ibb.co/ZL7DBJV/output-onlinepngtools.png",
       tutorial:"<p>Cream is <i>butter</i></p>",
       downloads:[
           {
            name:"SX",
            link:"https://mega.nz/#!4VVVEQCZ!AcURkXQy1lUFj2kPlb99H8OLtXYVa3aLzTxThBizhvk",
            version:"3.30"
           },
           {
            name:"SX",
            link:"https://www.lanzous.com/ia49hch",
            version:"3.10",
           }
       ],
       keys:[
           {
               keyType:"Day",
               keyPrice:"3",
               keyList:["daykey1","daykey2","daykey3"]
           },
           {
            keyType:"Week",
            keyPrice:"12",
            keyList:["weekkey1","weekkey2"]
           },
           {
            keyType:"Month",
            keyPrice:"18",
            keyList:["monthkey1"]  
            }
       ]
    },
    {
        name:"SX",
       game:"PUBG Mobile",
       typeOfProduct:"Hack",
       device:"Gameloop",
       image:"https://i.ibb.co/ZL7DBJV/output-onlinepngtools.png",
       tutorial:"<p>Cream is <i>butter</i></p>",
       downloads:[
           {
            name:"SX",
            link:"https://mega.nz/#!4VVVEQCZ!AcURkXQy1lUFj2kPlb99H8OLtXYVa3aLzTxThBizhvk",
            version:"3.30"
           },
           {
            name:"SX",
            link:"https://www.lanzous.com/ia49hch",
            version:"3.10",
           }
       ],
       keys:[
           {
               keyType:"Day",
               keyPrice:"3",
               keyList:["daykey1","daykey2","daykey3"]
           },
           {
            keyType:"Week",
            keyPrice:"12",
            keyList:["weekkey1","weekkey2"]
           },
           {
            keyType:"Month",
            keyPrice:"18",
            keyList:["monthkey1"]  
            }
       ]
    },
    {
        name:"SX",
       game:"PUBG Mobile",
       typeOfProduct:"Hack",
       device:"Gameloop",
       image:"https://i.ibb.co/ZL7DBJV/output-onlinepngtools.png",
       tutorial:"<p>Cream is <i>butter</i></p>",
       downloads:[
           {
            name:"SX",
            link:"https://mega.nz/#!4VVVEQCZ!AcURkXQy1lUFj2kPlb99H8OLtXYVa3aLzTxThBizhvk",
            version:"3.30"
           },
           {
            name:"SX",
            link:"https://www.lanzous.com/ia49hch",
            version:"3.10",
           }
       ],
       keys:[
           {
               keyType:"Day",
               keyPrice:"3",
               keyList:["daykey1","daykey2","daykey3"]
           },
           {
            keyType:"Week",
            keyPrice:"12",
            keyList:["weekkey1","weekkey2"]
           },
           {
            keyType:"Month",
            keyPrice:"18",
            keyList:["monthkey1"]  
            }
       ]
    }
]

async function seedDB(){
    //Delete All campgrounds
    try{
        // await Product.deleteMany({});
        for(const seed of seeds ){
            let product= await Product.create(seed);
            product.save();
        }
    }catch(err){
        console.log(err);
    }
    }
        

module.exports = seedDB;